topic_1:
  SEARCH_QUERY: psychology
  YOUTUBE_API_KEY: AIzaSyDDZaDiAIPPgo7PQdKFNuLcHmhbd17r658
  VIDEOS_LIMIT: 25
  COMMENTS_LIMIT: 500
  RELEVANCE_LANGUAGE: "en"
  REGION_CODE: "US"
  EXPERIMENT_NAME: "psychology__sentiment__tfidf"
