topic_1:
  SEARCH_QUERY: psychology
  YOUTUBE_API_KEY: AIzaSyDDZaDiAIPPgo7PQdKFNuLcHmhbd17r658
  VIDEOS_LIMIT: 5
  COMMENTS_LIMIT: 100
  RELEVANCE_LANGUAGE: "en"
  REGION_CODE: "US"
  EXPERIMENT_NAME: "psychology__sentiment_tfidf"
